export const BOARD_ICONS = [
  "clipboard-list",
  "layout-dashboard",
  "kanban",
  "folder",
  "briefcase",
  "rocket",
  "zap",
  "target",
  "trophy",
  "star",
  "heart",
  "flag",
  "bookmark",
  "code",
  "cpu",
  "database",
  "globe",
  "monitor",
  "smartphone",
  "settings",
  "users",
  "calendar",
  "bar-chart-3",
  "pie-chart",
  "lightbulb",
  "puzzle",
  "shield",
  "truck",
  "package",
  "shopping-cart",
] as const;

export type BoardIconName = typeof BOARD_ICONS[number];
