apiVersion: v1
kind: Service
metadata:
  name: {{ include "talep-yonetimi.fullname" . }}
  labels:
    {{- include "talep-yonetimi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "talep-yonetimi.selectorLabels" . | nindent 4 }}
